import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-white shadow-md">
          <div className="container mx-auto px-4 py-4 flex justify-between items-center">
              <Link href="/home" className="text-2xl font-bold text-gray-800">Restaurant</Link>
              <ul className="flex space-x-6">
                  <li><Link href="/" className="text-gray-800 hover:text-gray-600">Home</Link></li>
                  <li><Link href="/menu" className="text-gray-800 hover:text-gray-600">Menu</Link></li>
                  <li><Link href="/products" className="text-gray-800 hover:text-gray-600">Products</Link></li>
                  <li><Link href="/contact" className="text-gray-800 hover:text-gray-600">Contact</Link></li>
              </ul>
          </div>
        </nav>
        <main>{children}</main>
        <footer className="bg-gray-800 text-white py-8">
          <div className="container mx-auto text-center">
              <p className="mb-4">&copy; 2024 Restaurant Name. All rights reserved.</p>
              <ul className="flex justify-center space-x-6">
                  <li><a href="/privacy" className="hover:text-gray-400">Privacy Policy</a></li>
                  <li><a href="#" className="hover:text-gray-400">Terms of Service</a></li>
              </ul>
          </div>
        </footer>
        
      </body>
    </html>
  );
}
